- name: mysql setup
  hosts: all
  become: yes
  tasks:
    - name: copy mysql repo
      ansible.builtin.copy:
       src: mysql.repo
       dest: /etc/yum.repos.d/mysql.repo

    - name: disable default mysql version
      ansible.builtin.shell: yum module disable mysql -y

    - name: install mysql community version
      ansible.builtin.yum:
       name: mysql-community-server
       state: installed

    - name: start service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes

    - name: set root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1






#cp mysql.repo /etc/yum.repos.d/mysql.repo
#yum module disable mysql -y
#yum install mysql-community-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass ${mysql_root_password}